### ISSUE TITLE
'by' error 

### ISSUE THREAD

**Issue by vargovargo** [mcSamuelDataSci/CACommunityBurden#1]
when viewing census tract data on static map received 'by' error

**Comment by vargovargo** [comment]
this is the error
```
error 'by'
```

**Comment by mcSamuelDataSci** [comment]
Thanks for this reminder. The error was caused by using an older version of the "real" working data set, where "GEOID" was labeled as "geoid".  This error does not effect the repository on GitHub since in only has "fake" data, but was good to fix in any case.
