### ISSUE TITLE
Added RStudio Wiki instructions

### ISSUE THREAD

**Issue by mcSamuelDataSci** [mcSamuelDataSci/CACommunityBurden#13]
I just poked around, and made a "wiki" entry to use as instructions for our team to get set up for using git with RStudio.  Please review and comment if you have time/interest. Thanks.

**Comment by benjamin-hicks-cdph-ca-gov** [comment]
The [https://github.com/mcSamuelDataSci/CACommunityBurden/wiki](url) looks good. The only suggestions I have:
-correct the small typo in the file URL: c:\Users\YOURUSERNA**SME**\AppData\Local\Programs\Git\bin
-provide an image or description on where the new project button is in R. Something to the effect of "(in the top right corner, below the close program icon)"
-provide a description for where one would find the comment window. Something to the effect of "R-Git in the "command window" (Git CMD under the windows start menu)"

**Comment by mcSamuelDataSci** [comment]
Thanks Ben. I'd like to talk to you about the 2nd suggestion.
