### ISSUE TITLE
tmap general

### ISSUE THREAD

**Issue by mcSamuelDataSci** [mcSamuelDataSci/CACommunityBurden#25]
Zev-
At your suggestion I have begun migrating the mapping for this project to tmap. In the app, there is currently a "tmap" tab, a "static map" tab, and an "interactive map" tab.  Within two weeks I plan to have only the "tmap" tab (and i will be called just "Map" or something), with all of the functionality that is all three tabs currently.  At your request, I will start listing issues that are as specific as I can to help with this migration, and for now will be referring to all three of the tabs. 
Thanks,
Michael

**Comment by zross** [comment]
OK.
