### ISSUE TITLE
indexing to extract names

### ISSUE THREAD

**Issue by mcSamuelDataSci** [mcSamuelDataSci/CACommunityBurden#27]
Zev-
Is there a more "elegant" or transparent (for other users of my code) way to do the code below, in one case using two vectors, in the other using two columns of a dataframe?

nameVector[valueVector == myValue]

dataFrame[dataFrame[,1]== myValue,2]

**Comment by zross** [comment]
This doesn't give me much context but:

For your vector one I don't think there is a better way, though if you can make them data frames or tibbles I think this is clearer -- a table with both vectors as variables. But it depends.

On the data.frame, first off indexing by variable number is not good practice you should use the name of the variable in place of the `1` and `2`. I would probably write it more tidyverse ish as:

```r
dataFrame %>% filter(variable1 == myValue) %>% pull(variable2)
```

**Comment by mcSamuelDataSci** [comment]
Great!  I have never seen pull() before, and glad I am now.

The context is seen in lines 72 and 73 of this file: https://github.com/mcSamuelDataSci/CACommunityBurden/blob/master/myCBD/myFunctions/cbdMap-tmap.R
(a file to which I will be referring with a few more issues over the next week), where I am adding elements to a title based on this indexing.

**Comment by zross** [comment]
you can close this right?
