### ISSUE TITLE
one more test

### ISSUE THREAD

**Issue by mcSamuelDataSci** [mcSamuelDataSci/CACommunityBurden#30]
to test or not to test, that is the question

**Comment by benjamin-hicks-cdph-ca-gov** [comment]
Ben's comment on issue #30

**Comment by mcSamuelDataSci** [comment]
okay. Please make one last reply to this. Even though I created the issues, i did not get a notice since I had not assigned myself to the issue.

**Comment by benjamin-hicks-cdph-ca-gov** [comment]
Ben's comment on issue #30 second attempt.

**Comment by benjamin-hicks-cdph-ca-gov** [comment]
Not a problem. Comment made.

________________________________
