### ISSUE TITLE
Census tract merge issue

### ISSUE THREAD

**Issue by mcSamuelDataSci** [mcSamuelDataSci/CACommunityBurden#31]
Dave-
for consistency:
- the county "column" should be named "county", all lower case
- GEOID should be all upper cases, as you have it
- the "indicator" variable should use the format as I show on line 30 of the R file, or some other consitent form of your choosing
- the other variables/columns don't need to be renamed at all, since they are not used elsewhere in the CCB

**Comment by mcSamuelDataSci** [comment]
Any update on this Dave?

**Comment by dauphine33** [comment]
Yup, just pushed to you for the second time today.

**Comment by mcSamuelDataSci** [comment]
Great, thanks. When you do a push, please add a comment to that effect to this issue (and no need to paste anything in from the email that is automatically generated by these comments).
Thanks!

**Comment by mcSamuelDataSci** [comment]
Dave, please see my edits, and see if it all makes sense?  Some bits may be a bit "fancy" but still good for learning. Also, see lines 119-127 which are some "analysis" of these data.

**Comment by dauphine33** [comment]
Will do, mahalo y feliz Viernes senyor!

**Comment by dauphine33** [comment]
p.s. thought I did add a comment (as I think you said we usually should) but I didn’t do the pull request.

**Comment by dauphine33** [comment]
Looks good, just commented on another issue you assigned me that now I see is closed: “determine how to search files (including sub-directories) including R files for specific string” If you figured that out, I’ll get back to the ICD codes.

From: Dauphine, David@CDPH
Sent: Friday, August 31, 2018 8:00 AM
To: 'mcSamuelDataSci/CACommunityBurden' <reply@reply.github.com>
Subject: RE: [mcSamuelDataSci/CACommunityBurden] Census tract merge issue (#31)

Will do, mahalo y feliz Viernes senyor!

**Comment by mcSamuelDataSci** [comment]
Great Dave. I did figure out the file searching issue, and it's quiet cool, and it'd be fun to show it to you sometime. Great to get back to the ICD issue next week. Have a great weekend. 

PS, sending this to you from Bart on my phone on the way to an A's game. GitHub rocks.

**Comment by dauphine33** [comment]
Funny I’m listening to that game right now on mlb radio in Spanish. Waiting till afterwards you can skip commercials. Great background noise at work!
