### ISSUE TITLE
For starting app without real data change in two places

### ISSUE THREAD

**Issue by zross** [mcSamuelDataSci/CACommunityBurden#37]
@nteetor FYI when you try to run the repo the real app is in myCBD and you need to change from "real" to "fake" in two places because there is data he can't share. 

https://github.com/mcSamuelDataSci/CACommunityBurden/blob/master/myCBD/Global.R#L16

and if you're doing anything with data:

https://github.com/mcSamuelDataSci/CACommunityBurden/blob/master/myUpstream/makeDatasets.R#L22

**Comment by nteetor** [comment]
Thank you Zev, I did find the application toggle and was running the application locally with the fake data.

**Comment by mcSamuelDataSci** [comment]
Thank you both!
