### ISSUE TITLE
using sf in tmap

### ISSUE THREAD

**Issue by mcSamuelDataSci** [mcSamuelDataSci/CACommunityBurden#38]
I have migrated all the mapping in the CCB to tmap, and that’s great.  I was planning to migrate the “shape files” to “simple features”, but, as far as I can tell, tmap does not support this, with error message “conversion from feature type sfc_GEOMETRY to sp is not supported”.  I have done a bit of experimenting as you can see in lines 58-74 of [this file](https://github.com/mcSamuelDataSci/CACommunityBurden/blob/master/myCBD/Global.R) where the shapes are brought into the app. No error generated with tmap when I read in the (simple features shape files) with readOGR, but error with reading the same files in with st_read.
Specific questions:
1.	Do you think I should use the “shape files” as simple features objects?
2.	If so, how with tmap?

**Comment by mcSamuelDataSci** [comment]
Zev - any thoughts on this?

**Comment by zross** [comment]
tmap supports sf objects. What version are you using? Why don't you update tmap and see if it's still an isssue. If it's still an issue then point me to a reproducible example.

As an experiment you can also try `as(my_sf_thing, "Spatial")` within the call to tmap -- which converts sf to sp and see if that works (to test whether the sf object is valid in the first place).

**Comment by mcSamuelDataSci** [comment]
The map object were/are sf.  While trying to create the simplest possible reproducible example I found out that the issue was using "merge" to join the sf object to a dataframe. The object was still sf, but generated the error when mapping with tmap. When I switched to geo_join (from tigris) everything works!

**Comment by mcSamuelDataSci** [comment]
So....  the system is now working, but the data are clearly not merging correctly. I am trying a number of things, but may send a reproducible example soon.  Should I just join rather than geo_join?  I will keep working...

**Comment by mcSamuelDataSci** [comment]
wow, that was scary as I am under some major deadlines, and did not want to trouble shoot too much.

BUT, left_join works just fine!  geo_join does not...

**Comment by zross** [comment]
Yes, one of the great things about sf is that you can use your regular tidy tools and don't need to worry about merge vs geo_join etc messing things up.
